---
title: "Data Gathering"
author: "Marc Vitenzon"
date: "11/14/2021"
output: pdf_document
---

```{r}
library(quantmod)

symbols <- c("SPY", "VXX")
getSymbols(symbols, from="2019-01-02", to="2021-01-01")

price_data = data.frame(SPY$SPY.Adjusted,VXX$VXX.Adjusted)
colnames(price_data) <- symbols

data = read.csv("data_gathering (2).csv")
```

```{r}
library(TTR)

# all indicators related to the SPY
sma = as.numeric(SMA(price_data[,1]))
cci = as.numeric(CCI(price_data[,1]))
cmo = as.numeric(CMO(price_data[,1]))
macd = as.numeric(MACD(price_data[,1])[,1])
bbands = as.numeric(BBands(price_data[,1])[,4])
runSum = as.numeric(runSum(price_data[,1]))
fastK= as.numeric(stoch(price_data[,1])[,1])
fastD = as.numeric(stoch(price_data[,1])[,2])
slowD = as.numeric(stoch(price_data[,1])[,3])
tdi = as.numeric(TDI(price_data[,1])[,1])
trix = as.numeric(TRIX(price_data[,1])[,1])
volatility = as.numeric(volatility(price_data[,1]))
wpr = as.numeric(WPR(price_data[,1]))

# VXX daily returns
vxxReturns = dailyReturn(VXX, type="log")

indicator_df = data.frame(
  sma,
  cci,
  cmo,
  macd,
  bbands,
  fastK,
  fastD,
  slowD,
  tdi,
  trix,
  volatility
)

indicator_df = indicator_df[complete.cases(indicator_df), ] # not lagged or logs


library(corrplot)
corrplot(cor(indicator_df, use = "complete.obs"), method = "number")

#% change df
```

```{r}
library(TTR)

# all indicators related to the SPY
sma = as.numeric(SMA(price_data[,1]))
cci = as.numeric(CCI(price_data[,1]))
cmo = as.numeric(CMO(price_data[,1]))
macd = as.numeric(MACD(price_data[,1])[,1])
bbands = as.numeric(BBands(price_data[,1])[,4])
runSum = as.numeric(runSum(price_data[,1]))
fastK= as.numeric(stoch(price_data[,1])[,1])
fastD = as.numeric(stoch(price_data[,1])[,2])
slowD = as.numeric(stoch(price_data[,1])[,3])
tdi = as.numeric(TDI(price_data[,1])[,1])
trix = as.numeric(TRIX(price_data[,1])[,1])
volatility = as.numeric(volatility(price_data[,1]))
wpr = as.numeric(WPR(price_data[,1]))
zigZag = as.numeric(ZigZag(price_data[,1]))

# VXX daily returns
vxxReturns = dailyReturn(VXX, type="log")

indicator_df = data.frame(
  sma,
  cci,
  cmo,
  macd,
  bbands,
  fastK,
  fastD,
  slowD,
  tdi,
  trix,
  volatility
)

indicator_df = indicator_df[complete.cases(indicator_df), ] # not lagged or logs


library(corrplot)
corrplot(cor(indicator_df, use = "complete.obs"), method = "number")

indicator_df2 = data.frame(
  Delt(sma,type='arithmetic'),
  Delt(cci,type='arithmetic'),
  Delt(cmo,type='arithmetic'),
  Delt(macd,type='arithmetic'),
  Delt(bbands,type='arithmetic'),
  Delt(fastD,type='arithmetic'),
  Delt(slowD,type='arithmetic'),
  Delt(tdi,type='arithmetic'),
  Delt(volatility,type='arithmetic'),
  Delt(data$Euro.Spot...Last.Price..R1.[1:which(data$date == "12/31/2020")],type = "arithmetic"),
  Delt(data$US.TSA.Checkpoint.Numbers.Total.Traveler.Throughput...Last.Price..R1.[1:which(data$date == "12/31/2020")],type = "arithmetic"),
  Delt(data$Bloomberg.United.States.Financial.Conditions.Index...Last.Price..R2.[1:which(data$date == "12/31/2020")],type = "arithmetic"),
  Delt(data$CBOE.Equity.Put.Call.Ratio...Last.Price..R1.[1:which(data$date == "12/31/2020")],type = "arithmetic"),
  Delt(data$US.Put.Call.Ratio.Composite...Last.Price..L1.[1:which(data$date == "12/31/2020")],type = "arithmetic"),
  Delt(data$Bloomberg.Cumulative.Advance.Decline.Line.for.S.P.500...Last.Price..R1.[1:which(data$date == "12/31/2020")],type = "arithmetic"),
  Delt(data$McClellans.Advances...Declines.US.Index.Summation...Last.Price..R1.[1:which(data$date == "12/31/2020")],type = "arithmetic"),
  Delt(data$S.P.500.Composite.Volume.Index...Last.Price..R1.[1:which(data$date == "12/31/2020")],type = "arithmetic"),
  Delt(data$Cboe.Realized.Volatility.Index...Last.Price..R1.[1:which(data$date == "12/31/2020")],type = "arithmetic"),
  Delt(data$Cboe.Implied.Correlation.Index...Last.Price..R1.[1:which(data$date == "12/31/2020")],type = "arithmetic"),
  Delt(data$Base.Metals.Spot.Price.Index...Last.Price..R1.[1:which(data$date == "12/31/2020")],type = "arithmetic")
)

colnames(indicator_df2) <- c("sma", "cci", "cmo", "macd", "bbands", "fastD", "slowD", "tdi", "vol", "EuroSpot", "US TSA Numbers", "BBG Financial Conditions", "CBOE Equity Put/Call", "US Put Call Composite", "BBG Adv/Dec SPX", "US Adv/Dec", "SPX Composite Volume", "CBOE rVol", "CBOE Implied Cor.", "Base Metals Spot Index")
rownames(indicator_df2) <- rownames(price_data)
View(indicator_df2)
View(vxxReturns)
nrow(indicator_df2[1:(nrow(indicator_df2)-5),])
nrow(vxxReturns[6:(nrow(vxxReturns)),])
###########################################################################################################################
### This modifies the lag of the model - change 7 to what you want the lag to be, and change 6 to your desired lag - 1 on the next line
#############################################################################
lag = 5

lagged_df2 <- indicator_df2[1:(nrow(indicator_df2)-lag),]
lagged_df2$vxxReturns <-  vxxReturns[(lag+1):(nrow(vxxReturns)),]
lagged_df2 <- na.omit(lagged_df2)
lagged_df2 <- lagged_df2[!is.infinite(rowSums(lagged_df2)),]

View(lagged_df2) 
#indicator_df2 = indicator_df2[-na.omit(indicator_df2), ]
corrplot(cor(lagged_df2, use = "complete.obs"), method = "pie")

```

```{r}
train=sample(length(lagged_df2),length(lagged_df2)*.8,replace=FALSE) #Train/Test split

library(glmnet)

lin.mod = glm(lagged_df2$vxxReturns~.,data=lagged_df2,subset=train)

lin.pred=predict(lin.mod,lagged_df2[train,])
mean((lin.pred-lagged_df2$vxxReturns[train])^2)
summary(lin.mod)

lin.pred=predict(lin.mod,lagged_df2[-train,])
mean((lin.pred-lagged_df2$vxxReturns[-train])^2)
```

```{r}
train=sample(length(lagged_df2),length(lagged_df2)*.8,replace=FALSE) #Train/Test split

library(glmnet)

lin.mod = glm(lagged_df2$vxxReturns~.,data=lagged_df2,subset=train)
summary(lin.mod)
mean((lagged_df2$vxxReturns[train] - predict(lin.mod, lagged_df2[train,]))^2)

lin.pred=predict(lin.mod,lagged_df2[-train,])
mean((lin.pred-lagged_df2$vxxReturns[-train])^2)

```

```{r}
library(tree)
lagged_df2 <- data.frame(lagged_df2)
tree.reg = tree(lagged_df2$vxxReturns~.,data=lagged_df2,subset=train)


mean((lagged_df2$vxxReturns[train] - predict(tree.reg, lagged_df2[train,]))^2) #Training MSE

y.tree.pred = predict(tree.reg, lagged_df2[-train,]) # Predict with the single regression tree
tree.MSE = mean((lagged_df2$vxxReturns[-train] - y.tree.pred)^2)
tree.MSE #Test MSE

```
```{r}
library(randomForest)

rf.reg = randomForest(lagged_df2$vxxReturns~.,data=lagged_df2,subset=train,mtry=3,ntree=300,importance=TRUE)
rf.reg #Gives both the number of variables at each split but also provides out-of-bag estimate of error rate

mean((lagged_df2$vxxReturns[train] - predict(rf.reg, lagged_df2[train,]))^2) # Train MSE

y.rf.pred = predict(rf.reg, lagged_df2[-train,]) 
rf.MSE = mean((lagged_df2$vxxReturns[-train] - y.rf.pred)^2)
rf.MSE # Test MSE
```

```{r}
getSymbols(symbols, from="2021-01-02", to="2021-11-11")

price_data = data.frame(SPY$SPY.Adjusted,VXX$VXX.Adjusted)
colnames(price_data) <- symbols

# all indicators related to the SPY
indicator_df2 = data.frame(
 # Delt(sma,type='arithmetic'),
  #Delt(cci,type='arithmetic'),
  #Delt(cmo,type='arithmetic'),
  #Delt(macd,type='arithmetic'),
  #Delt(bbands,type='arithmetic'),
  #Delt(fastD,type='arithmetic'),
  #Delt(slowD,type='arithmetic'),
  #Delt(tdi,type='arithmetic'),
  #Delt(volatility,type='arithmetic'),
  Delt(data$Euro.Spot...Last.Price..R1.[1:which(data$date == "12/31/2020")],type = "arithmetic"),
  Delt(data$US.TSA.Checkpoint.Numbers.Total.Traveler.Throughput...Last.Price..R1.[which(data$date == "1/4/2021"):which(data$date == "11/11/2021")],type = "arithmetic"),
  Delt(data$Bloomberg.United.States.Financial.Conditions.Index...Last.Price..R2.[which(data$date == "1/4/2021"):which(data$date == "11/11/2021")],type = "arithmetic"),
  Delt(data$CBOE.Equity.Put.Call.Ratio...Last.Price..R1.[which(data$date == "1/4/2021"):which(data$date == "11/11/2021")],type = "arithmetic"),
  Delt(data$US.Put.Call.Ratio.Composite...Last.Price..L1.[which(data$date == "1/4/2021"):which(data$date == "11/11/2021")],type = "arithmetic"),
  Delt(data$Bloomberg.Cumulative.Advance.Decline.Line.for.S.P.500...Last.Price..R1.[which(data$date == "1/4/2021"):which(data$date == "11/11/2021")],type = "arithmetic"),
  Delt(data$McClellans.Advances...Declines.US.Index.Summation...Last.Price..R1.[which(data$date == "1/4/2021"):which(data$date == "11/11/2021")],type = "arithmetic"),
  Delt(data$S.P.500.Composite.Volume.Index...Last.Price..R1.[which(data$date == "1/4/2021"):which(data$date == "11/11/2021")],type = "arithmetic"),
  Delt(data$Cboe.Realized.Volatility.Index...Last.Price..R1.[which(data$date == "1/4/2021"):which(data$date == "11/11/2021")],type = "arithmetic"),
  Delt(data$Cboe.Implied.Correlation.Index...Last.Price..R1.[which(data$date == "1/4/2021"):which(data$date == "11/11/2021")],type = "arithmetic"),
  Delt(data$Base.Metals.Spot.Price.Index...Last.Price..R1.[which(data$date == "1/4/2021"):which(data$date == "11/11/2021")],type = "arithmetic")
)

rownames(indicator_df2) <- c(as.character(data$date[which(data$date == "1/4/2021"):which(data$date == "11/11/2021")]))


vxxReturns = dailyReturn(VXX, type="arithmetic")
nrow(indicator_df2[1:(nrow(indicator_df2)-5),])
nrow(vxxReturns[6:(nrow(vxxReturns)),])
###########################################################################################################################
### This modifies the lag of the model - change 7 to what you want the lag to be, and change 6 to your desired lag - 1 on the next line
#############################################################################
indicator_df2 <- indicator_df2[1:(nrow(indicator_df2)-5),]
indicator_df2$vxxReturns <-  vxxReturns[5:(nrow(vxxReturns)),]
indicator_df2 <- na.omit(indicator_df2)
indicator_df2 <- indicator_df2[!is.infinite(rowSums(indicator_df2)),]
y.rf.pred = predict(rf.reg, indicator_df2) 

result <- data.frame(y.rf.pred)


View(result)
result$direction <- (result$y.rf.pred >0) +0
result$date <- rownames(result)
vol_expected <- data.frame(result[which(result$direction == 1),])
vol_expected$date <- as.Date(rownames(vol_expected))

View(vol_expected)
###########################################################################################################################
### This modifies for how far out you begin to go risk-off after the signal is triggered. Ex: 5 means 5 days after the signal is triggered go risk off
#############################################################################
for (i in 1:nrow(vol_expected)){
  vol_expected$date[i] <- vol_expected$date[i]+5
}


price_data$date <- rownames(price_data)
price_data$VXX_direction_pred <- 0

for(i in 1:nrow(price_data)){
  for (j in 1: nrow(vol_expected)){
    if(price_data$date[i] == vol_expected$date[j]){
    price_data$VXX_direction_pred[i] <- 1
    }
  }
}

price_data$port <- 100
price_data$spy_port <- 100

###########################################################################################################################
### This modifies for how many days the model goes risk-off once the signal gets triggered, change 5 to your desired period
#############################################################################
counter = 0;
for(i in 1:nrow(price_data)){
  if (i != nrow(price_data)){
  if(price_data$VXX_direction_pred[i] == 1){
    if (counter != 6){
      price_data$VXX_direction_pred[i+1] <- 1
      counter = counter + 1
    } else {
      counter = 0
      price_data$VXX_direction_pred[i+1] <- 0
    }
  }
  }
}

price_data$spy_ret <- dailyReturn(SPY$SPY.Adjusted, type = "arithmetic")
price_data$port_ret <- dailyReturn(SPY$SPY.Adjusted, type = "arithmetic")


for(i in 1:nrow(price_data)){
  if(price_data$VXX_direction_pred[i] == 1){
    price_data$port_ret[i] <- 0
  }
}



for(i in 2:nrow(price_data)){
  price_data$spy_port[i] <- price_data$spy_port[i-1] * (1+price_data$spy_ret[i-1])
  price_data$port[i] <- price_data$port[i-1] * (1+price_data$port_ret[i-1])
}

library(ggplot2)
library(reshape2)

final_result <- cbind(price_data$port,price_data$spy_port)
rownames(final_result) <- rownames(price_data)
colnames(final_result) <- c("Portfolio Return", "SPY Return")
rownames(final_result) <- rownames(price_data)
final_result <- data.frame(final_result)
final_result$date <- as.Date(rownames(final_result))

sharpe_ratios <- data.frame(matrix(0,nrow = 2,2))
sharpe_ratios[1,1] <- (mean(price_data$port_ret))/sd(price_data$port_ret)
sharpe_ratios[1,2] <-(mean(price_data$spy_ret))/sd(price_data$spy_ret)
sharpe_ratios[2,1] <- sd(price_data$port_ret)
sharpe_ratios[2,2] <- sd(price_data$spy_ret)
colnames(sharpe_ratios) <- c("Portfolio", "SPY")
rownames(sharpe_ratios) <- c("Sharpe", "Standard Deviation")

final_result <- melt(final_result, id = "date")


ggplot(final_result, aes(x = final_result$date, y = final_result$value, color = variable, group = final_result$variable))+geom_line()+ scale_x_date(date_minor_breaks = "1 day") + labs(color = "Portfolio") + xlab("Date") + ylab("Portfolio Value") + ggtitle("Model Performance vs. SPY") 




```
